Implement SEQ Instruction
corewar-teamprojekt/corewar pull request #163
Opened 2024-11-03 21:30 UTC by nikkischnelle

This is the first instruction I'm implementing, so I'm just gonna open this as a draft for discussion.

2024-11-04 15:32 UTC, flamion commented
Looks good, but 2 things:
- I would like more descriptive naming of the tests instead of just "XXXMatch" and "XXXNoMatch"
- SEQ is just a rename of the CMP - the instructions both do the same thing. The story related to this pull request even has it as a requirement that there are no separate implementations for both

2024-11-04 15:50 UTC, nikkischnelle commented
I didn't see that Compare was implemented, because it isn't named CMP.kt
So Compare is already implemented, but why does the Parser call Seq for both the CMP and SEQ token?
![image](https://github.com/user-attachments/assets/a3d9a886-6d10-47dc-8244-d8de015fac71)

And why do both Compare.kt and SEQ.kt even exist if the parser just points to _one_ implementation?

2024-11-04 15:52 UTC, flamion commented
> I didn't see that Compare was implemented, because it isn't named CMP.kt So Compare is already implemented, but why does the Parser call Seq for both the CMP and SEQ token? ![image](https://private-user-images.githubusercontent.com/67095634/382820930-a3d9a886-6d10-47dc-8244-d8de015fac71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzU3NTEsIm5iZiI6MTczMDczNTQ1MSwicGF0aCI6Ii82NzA5NTYzNC8zODI4MjA5MzAtYTNkOWE4ODYtNmQxMC00N2RjLTgyNDQtZDhkZTAxNWZhYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE1NTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MDAzMDczMTQ1NzUxZTA5NjU2Mzk0MTA0NTRkMTdlN2U4ZWY4NmU0NTAyMzEyM2M3OWRhODZiNmE5ZmNhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sMRzdPFwKySwN3ys5AgvXwFy3lF2aM2Dnw4Ub3h1nHk)
> 
> And why do both Compare.kt and SEQ.kt even exist if the parser just points to _one_ implementation?

Because after #163 is done, CMP should just be an alias for SEQ. We can continue with this implementation, however then CMP should be just an alias for SEQ. SEQ is preferred as it fits in with the other jumping-instructions and came later as a "replacement"

2024-11-04 15:56 UTC, nikkischnelle commented
But because both files exists, there was an existing implementation of CMP which we could have used instead, so we just did double the work. It wasn't much work, but should still be avoided in the future.
And in light of your second comment, I don't really understand the second point of your first comment

> - SEQ is just a rename of the CMP - the instructions both do the same thing. The story related to this pull request even has it as a requirement that there are no separate implementations for both

because that requirement is fulfilled by this implementation (because it had already been fullfilled beforehand)

2024-11-04 15:59 UTC, flamion commented
> But because both files exists, there was an existing implementation of CMP which we could have used instead, so we just did double the work. It wasn't much work, but should still be avoided in the future. And in light of your second comment, I don't really understand the second point of your first comment
> 
> > * SEQ is just a rename of the CMP - the instructions both do the same thing. The story related to this pull request even has it as a requirement that there are no separate implementations for both
> 
> because that requirement is fulfilled by this implementation (because it had already been fullfilled beforehand)

We had decided while planning that an implementation for CMP should still exist, even if it just proxies an SEQ (for example by just extending SEQ but not overriding anything) - We could also just move the CMP implementation to the SEQ implementation, maybe we can discuss this in the interpreter team

2024-11-04 16:01 UTC, nikkischnelle commented
That should have been made clear in the issue. It says

> - [ ] SEQ instruction has been implemented according to spec
> - [ ] Made sure that CMP is just an alias for SEQ and doesn't exist separately

which, to me, very clearly reads that CMP is an alias and SEQ contains the actual implementation, not the other way around.

2024-11-04 16:15 UTC, nikkischnelle commented
Ok after a small side-discussion with @flamion :
- use this implementation
- make Cmp.kt a :socks: for the Seq.kt implementation
- adjust Parser so it calls Cmp.kt for `CMP` Tokens and Seq.kt for `SEQ` Tokens
- adjust the tests accordingly

did I miss something?

2024-11-04 16:24 UTC, flamion commented
> Ok after a small side-discussion with @flamion :
> 
>     * use this implementation
> 
>     * nuke current Compare.kt
> 
>     * future issues will contain more detail about the context they were created in
> 
> 
> did I miss something?

Nothing missed from what I can tell

2024-11-05 12:06 UTC, flamion requested changes

2024-11-05 12:06 UTC, flamion commented on Containerfile.dev
Why is this in this PR? This doesn't have anything to do with the SEQ Instruction?

2024-11-05 12:07 UTC, nikkischnelle commented on Containerfile.dev
why is it even existent is the question. I drafted this yesterday but tought I scrapped it... was in a different branch entirely :D

2024-11-05 12:09 UTC, flamion approved these changes

2024-11-05 12:10 UTC, merged