#76 Implement SHORK Settings
corewar-teamprojekt/corewar pull request #233
Opened 2024-11-08 20:37 UTC by nikkischnelle

There were some issues testing options
- initialProgramCount
- seperation
Both are only used in the `Shork`s `run` method. Because the MemoryCore gets initiated at the start of the function and all references dropped at the end, we can only observe who won when calling `run`.
@flamion and I agreed to open a new Issue for testing `seperation`, as the way `run` works should change soon and testing `seperation` might be possible afterward. 

The way address resolving works had to be changed substantially because of the `readDistance` and `writeDistance` settings.  
(Because of this, each time a new instruction is implemented, I will have to alter this PR. So do not merge right after merging of a new instruction)

2024-11-08 22:01 UTC, flamion requested changes

2024-11-08 22:18 UTC, nikkischnelle commented on backend/shork/src/main/kotlin/Settings.kt
> +    /** The number of instructions between two processes when created */
the minimum is another setting, though.
This is the setting for the distance, if it is not random (so always x)
minimumSeparation is further up in the file and is the minimum if separationRandom is true

2024-11-08 22:19 UTC, nikkischnelle commented on backend/shork/src/main/kotlin/Settings.kt
> +    val randomSeparation: Boolean = false,
Yes. minimumSeparation is another value further up in the file.
`separation` is the value used if `randomSeparation` is false

2024-11-08 22:20 UTC, nikkischnelle commented on backend/shork/src/main/kotlin/Settings.kt
> +    val initialProgramCount: Int = 1,
This is what I understood the  `Warriors` variable to be. 
http://www.koth.org/info/icws94.html#4.2
Is it not?

2024-11-08 22:24 UTC, nikkischnelle commented on backend/shork/src/main/kotlin/Shork.kt
> +                    }
The minimum is respected when using randomSeparation. `internalSettings.minimumSeparation + {random}`

I couldn't find any documentation on how the minimum is interpreted if a specific separation value is set. What do you think that should look like? I also thought about `minimumSeparation + separation` and `if (minimumSeparation > separation) { minimumSeparation}`

2024-11-10 14:32 UTC, flamion requested changes

2024-11-10 14:32 UTC, flamion commented on backend/shork/src/main/kotlin/Settings.kt
> +    val initialProgramCount: Int = 1,
Well yes, but the initial programs depends on the amount of players
n players = n warriors = n programs
The initial amount of programs is simply not configurable (unless you count the amount of players handed over to the shork in the initial run call (player : sourceCode mapping) as configuration)

2024-11-10 14:32 UTC, flamion commented on backend/shork/src/main/kotlin/Settings.kt
> +    val randomSeparation: Boolean = false,
You're right, I misread something.

2024-11-10 14:35 UTC, flamion commented on backend/shork/src/main/kotlin/Settings.kt
> +    val initialProgramCount: Int = 1,
I can't find it in the spec, can you point me to it?

2024-11-10 14:37 UTC, flamion commented on backend/shork/src/main/kotlin/Settings.kt
> +    val initialProgramCount: Int = 1,
Ah wait, I've found it now. I don't think it is needed, as this is implicitely provided to use via the player : sourceCode mapping, so this should be used instead

2024-11-10 14:37 UTC, nikkischnelle commented on backend/shork/src/main/kotlin/Shork.kt
> +            for (i in 0 until internalSettings.initialProgramCount) {
No, the way this setting works atm is:
Let's assume two players with a program each.
The default behaviour (with this setting as `1`) is: for each player, one of their programs is spawned
So playerAs program is spawned somewhere and playerBs program is spawned somewhere else

The behaviour with this setting set to `2` for example, is: 
for each player, two of their programs are spawned.
playerAs program is spawned twice at two different locations.

2024-11-10 14:39 UTC, nikkischnelle commented on backend/shork/src/main/kotlin/Shork.kt
> +                    shork.memoryCore.storeAbsolute(address++, instruction)
![image](https://github.com/user-attachments/assets/44e1672e-cb4d-445b-b3b3-9a5c8acd0d3b)
lmao

2024-11-10 14:43 UTC, nikkischnelle commented on backend/shork/src/main/kotlin/Settings.kt
> +    val initialProgramCount: Int = 1,
So for this PR I just take it out, yes?

2024-11-10 14:47 UTC, flamion commented on backend/shork/src/main/kotlin/Shork.kt
> +            for (i in 0 until internalSettings.initialProgramCount) {
![image](https://github.com/user-attachments/assets/a619ae58-500d-43d1-b241-fbb996309688)
The official pMARS implementation interprets it as number of players

2024-11-10 15:17 UTC, flamion commented on backend/shork/src/main/kotlin/Settings.kt
> +    val initialProgramCount: Int = 1,
> So - for this PR - I just take it out, yes?

Yes. The previous loop should be used (iterating simply over the pairs of player : sourceCode)

2024-11-14 09:58 UTC, flamion commented on backend/shork/src/test/kotlin/memory/TestMemoryCore.kt
> +    }
Is there an @Test missing above this function? Like this it wont be run when running the tests.

2024-11-14 10:01 UTC, flamion commented on backend/shork/src/main/kotlin/Shork.kt
> +            logger.info("Creating process for $player at address $address")
I've found the first log message more descriptive of what's actually happening. This suggests a process is created, for example via a SPL

2024-11-14 10:19 UTC, flamion approved these changes

2024-11-14 10:21 UTC, merged