201 extend header with lobby display copy button
corewar-teamprojekt/corewar pull request #259
Opened 2024-11-19 15:52 UTC by 0815Sailsman

Still WIP

2024-11-21 15:22 UTC, Straczi requested changes
as user i would like to have some kind of feedback when the lobbyId has been copied into my clipboard. Maybe add some onHover text saying "copy lobbyID to clipboard" and display a small toast or a small message above the button saying "copied!"

Edit: also a little bit more feedback that the button is actually a button and clickable would be nice (maybe in form of a small onHover effect that makes the button a litte bit more grey)

2024-11-22 01:25 UTC, 0815Sailsman commented on frontend/app/src/components/header/Header.tsx
> +		}
yep, this was for testing purposes and I forgot to remove it

2024-11-22 01:25 UTC, 0815Sailsman commented on frontend/app/src/TestFactories.ts
> +}
No particular reason, could also inline the types 🤷🏻

2024-11-22 01:33 UTC, 0815Sailsman commented on frontend/app/src/TestFactories.ts
> +}
but I think that looks a little too cluttered tbh

2024-11-25 21:08 UTC, merged