206 make all instructions immutable
corewar-teamprojekt/corewar pull request #260
Opened 2024-11-19 16:03 UTC by flamion

2024-11-20 16:04 UTC, PietHelzel requested changes

2024-11-20 17:03 UTC, flamion commented on backend/shork/src/main/kotlin/internal/instruction/AbstractInstruction.kt
> +    fun <T> write(block: (MutableAbstractInstruction) -> T): Pair<AbstractInstruction, T> {
How about `writeToMemory`?

2024-11-20 17:03 UTC, flamion commented on backend/shork/src/main/kotlin/internal/instruction/AbstractInstruction.kt
> +)
Yeah, I had the same thought but couldn't come up with a better name

2024-11-20 17:29 UTC, PietHelzel commented on backend/shork/src/main/kotlin/internal/instruction/AbstractInstruction.kt
> +    fun <T> write(block: (MutableAbstractInstruction) -> T): Pair<AbstractInstruction, T> {
Sounds good

2024-11-26 09:31 UTC, PietHelzel approved these changes
lgtm

2024-11-26 09:48 UTC, merged