300 update get lobbylobbyidstatus to return game data
corewar-teamprojekt/corewar pull request #301
Opened 2024-12-03 13:33 UTC by flamion

2024-12-03 14:21 UTC, TR1NITROTOLUOL submitted a review, later dismissed
Nice little adjustments to old tests and some code cleanup. I like those changes. The rest seems fine to me. Not necessarily a change request, but have you considered to add negative cases for the new tests e.g. trying to get the visualisation data before a game is finished? All in all i would approve, as it is now.

2024-12-03 19:23 UTC, flamion commented
> Nice little adjustments to old tests and some code cleanup. I like those changes. The rest seems fine to me. Not necessarily a change request, but have you considered to add negative cases for the new tests e.g. trying to get the visualisation data before a game is finished? All in all i would approve, as it is now.

You're right, I'll add a negative test

2024-12-04 07:26 UTC, TR1NITROTOLUOL submitted a review, later dismissed
No further remarks from me. Looks good to me.

2024-12-04 09:17 UTC, nikkischnelle commented on backend/api/src/test/kotlin/software/shonk/adapters/incoming/ShorkInterpreterControllerV1IT.kt
> +    // Workaround for content negotiation plugin bullshit
I don't know if we want this comment in main :sweat_smile:

2024-12-04 09:24 UTC, nikkischnelle requested changes

2024-12-04 09:24 UTC, nikkischnelle commented on backend/api/src/test/kotlin/software/shonk/application/service/ShorkServiceTest.kt
> +    fun `game visualization data works`() {
This doesn't really test if it "works" just that there is data. The Test name should reflect that imo

2024-12-04 09:30 UTC, nikkischnelle approved these changes
lgtm

![catspin](https://cdn.betterttv.net/emote/63651d249013520589f560f4/1x.webp)

2024-12-04 09:31 UTC, merged