Bug fix: POST with missing lobby response to 404
corewar-teamprojekt/corewar pull request #313
Opened 2024-12-04 21:07 UTC by nikkischnelle

Closes #308 

Changes POST to `/lobby/{lobbyId}/code/{player}` behaviour to respond with 404 if the lobby doesn't exist yet.

Will probably merge once there's one approval and no other change-requests

2024-12-04 21:43 UTC, TR1NITROTOLUOL submitted a review, later dismissed
Good improvements/adjustments to the tests. Like those changes. All in all I approve!

2024-12-04 23:46 UTC, steinerthelion approved these changes
Code looks good, changes are efficient and well-implemented

2024-12-04 23:53 UTC, flamion requested changes

2024-12-04 23:53 UTC, flamion commented on backend/api/src/test/kotlin/software/shonk/adapters/incoming/ShorkInterpreterControllerV1IT.kt
> +    inner class GetAndPostPlayerCode {
I don't really like the naming of this class / scope.
Something like `Create and read back player code` or smth like that would be better imo

2024-12-04 23:53 UTC, flamion commented on backend/api/src/test/kotlin/software/shonk/adapters/incoming/ShorkInterpreterControllerV1IT.kt
> +    inner class GetLobbies {
Something like GetAllLobbies would be better imo

2024-12-05 10:23 UTC, flamion approved these changes

2024-12-05 11:10 UTC, merged